config/v2/manifest.json, config/v3/manifest.json
Need an updated version of the extension to make certain extension stores live.
=> update version to push extensions live.

src/js/contentUtils.js
This will let us load it from cache.
=> Fetch src scripts in the content script, rather than in the service worker.

config/v2/manifest.json, config/v3/manifest.json, src/js/contentUtils.js
ensuring extension compares scripts in iframe to top level manifest and adding match_about_blank to manifest
=> No Frame Inspection

config/v3/manifest.json, src/js/background.js, src/js/contentUtils.js
checking fromCache for each script to make sure cached version of script was used for validation, and adding whatsapp url to host_permissions in v3 manifest
=> External Script Verification Bypass

src/js/contentUtils.js
This fixes sourceURL (and sourceMappingURL) comment stripping for data-uri scripts, and adds in the following assumptions for security reasons:
1. Script data-uris must start with `data:application/x-javascript` (that's a given)
2. For security reasons, any `//# sourceURL=` and `//# sourceMappingURL=` comments must exist at the bottom, and can optionally be only surrounded by whitespace.
Any data scripts that fail to do the above will get hashed as-is and (likely) fail verification in the extension.
We decide at runtime when to send down a script as an inline data script (i.e. with the script contents in the script url itself as a base64 data-uri), or as normal script tags with `https://` source URIs. As a result, inlined data scripts have an additional `//# sourceURL` comment that didn't …
=> Fix sourceURL comment stripping from data scripts

src/js/__tests__/contentUtils-test.js
Had to brute force some of these tests into submission, please advise. Seems like these haven't been run in a long time.
Gotta add some github actions fro the tests
=> Fix all broken content tests

jest.config.js, package.json, src/js/__tests__/background-test.js, src/js/__tests__/contentUtils-test.js, src/js/background.js, src/js/tab_state_tracker/TabStateMachine.ts, tsconfig.json, yarn.lock
The Typescript PR kinda broke the tests again, so this commit makes Jest work with TS.
=> Fix tests to play nice with typescript

src/js/contentUtils.js
Implement stricter checks around the manifest itself.
=> Improve checks around manifest script tag

src/js/contentUtils.js
We were not checking for invalid Uris when only the attributes of an element changed, this PR fixes that.
Ensure both of these cases error
=> Fix invalid uri checks for all elements

.github/workflows/tests.js.yml, build/rollup-plugin-clean-once.mjs, build/rollup-plugin-prettier-build-start.mjs, build/rollup-plugin-static-files.mjs, build/rollup-plugin-watch-additional.mjs, build/utils.mjs, package.json
Simplify package.json commands.
Tested to make sure all commands work.
=> Build commands

src/js/content/downloadJSArchive.ts, src/js/contentUtils.js, src/js/index.d.ts
Testing:
- Ensured archive downloads still work
=> Move download source functionality to TS

config/v3/manifest.json, src/js/background.ts
This listener was not correctly setup.
=> Fix no-cache listener

src/js/background.ts, src/js/background/setupNoCacheListeners.ts, src/js/background/tab_state_tracker/TabStateMachine.ts, src/js/content/alertBackgroundOfImminentFetch.ts, src/js/content/checkCSPHeaders.ts, src/js/content/checkElementForViolatingAttributes.ts, src/js/content/checkElementForViolatingJSUri.ts, src/js/content/sendMessageToBackground.ts, src/js/content/updateCurrentState.ts, src/js/contentUtils.ts, src/js/shared/MessageTypes.d.ts
- Pull out sendMessage -> sendMessageToBackground.ts
- Fix some TS warnings
- Create type for message responses for consistency between content/Bg
-
=> improve message types

src/js/background/tab_state_tracker/TabStateMachine.ts, src/js/content/alertBackgroundOfImminentFetch.ts, src/js/content/checkCSPHeaders.ts, src/js/content/checkElementForViolatingAttributes.ts, src/js/content/checkElementForViolatingJSUri.ts, src/js/content/downloadJSArchive.ts, src/js/content/genSourceText.ts, src/js/content/isPathNameExcluded.ts, src/js/content/updateCurrentState.ts, src/js/contentUtils.ts, src/js/detectFBMeta.ts, src/js/index.d.ts, src/js/shared/MessageTypes.d.ts, src/js/shared/sendMessageToBackground.ts
- Further simplify contentUtils.js
- Pull out more utils to own files
- Remove remaining `any` types
=> Further simplify contentUtils.js

_locales/en/messages.json, config/v2/manifest.json, config/v3/manifest.json, rollup.config.ts, src/js/background.ts, src/js/background/setupCSPListener.ts, src/js/config.ts, src/js/contentUtils.ts, src/js/detectIGMeta.ts, src/js/popup.ts, src/js/shared/isFbMsgrOrIgOrigin.ts
- Add support for instagram.com
- Added additional description to state update events (better console logging)
- Minor version bump
=> Add support for instagram.com

config/v2/manifest.json, config/v3/manifest.json, package.json
To include previous fix in upcoming release
=> Patch version bump

src/js/background/setupCSPListener.ts
I was noticing issues where CV would fail on first load, I narrowed it down to incorrect frameID attribution on the initial load of browser prerendered pages which was non-zero for some reason. This broke our CSP logic because CSPs ended up being saved for the wrong frame.
https://developer.chrome.com/blog/prerender-pages/
Testing:
Loaded two document scenarios: 'prerendered' and 'active' and made sure CV verifies correctly.
=> fix csp checks on prerendered documents

src/js/config.ts
Added a comment to KNOWN_EXTENSION_HASHES and moved the dynamic scripts entries into comments.
=> Clarify KNOWN_EXTENSION_HASHES

src/js/__tests__/contentUtils-test.js, src/js/background/validateManifest.ts, src/js/background/validateSender.ts, src/js/content/checkElementForViolatingJSUri.ts, src/js/content/genSourceText.ts, src/js/content/parseFailedJSON.ts, src/js/contentUtils.ts, src/js/popup.ts
Build was complaining about non-null-assertion (s) from recent strictifying, removing them to have a cleaner output.
https://typescript-eslint.io/rules/no-non-null-assertion/
=> remove non null assertions

src/js/__tests__/checkWorkerEndpointCSP-test.js
Similar to #275, but for the worker tests:
- I'm calling the granular functions (`areBlobAndDataExcluded`, `isWorkerSrcValid`)  instead of the top level function (`checkWorkerEndpointCSP`), expect for a couple sanity check tests.
- I deleted the "Invalid if eval allowed by CSP" test, since we already have tests for this method elsewhere.
=> Make worker tests more granular

src/js/__tests__/parseFailedJSON-test.js
This wasn't failing the build because it's in a test file, but worth cleaning up so we have a clean lint output.
=> Fix lint error

src/js/contentUtils.ts
Pure refactor for readability. Extracts the code for handling manifest nodes and script nodes out of `storeFoundJS` and into `handleManifestNode` and `handleScriptNode`.
=> Refactor storeFoundJS

_locales/en/messages.json, src/css/popup.css, src/html/popup.html
Remove debug popup, along with css + content.
Change download button to use it's own css.
+ Prettier changes
=> Remove unused debug poppup

_locales/en/messages.json, src/css/popup.css, src/html/popup.html, src/js/contentUtils.ts, src/js/popup.ts
Add a button that links to endpoints allowing download of the full release code (fb/ig/msgr).
=> Add a download release code button

src/js/detectWAMeta.ts
https://stackoverflow.com/questions/6724515/what-is-the-purpose-of-the-html-no-js-class/6724530#6724530
=> Tweak WA check for both js/no-js

config/v2/manifest.json, config/v3/manifest.json
CV should run on all subdomains.
=> Align Whatsapp manifest entries with rest of sites

README.md, rollup.config.ts
- Update README to reflect Safari support
- Add safari to build step (the output of this command is fed into [`safari-web-extension-converter`](https://developer.apple.com/documentation/safariservices/safari_web_extensions/converting_a_web_extension_for_safari)
=> Safari Support!

package.json
Ran a build with node 19 and 20
=> Bump supported node versions

src/js/__tests__/contentUtils-test.js, src/js/background.ts, src/js/contentUtils.ts, src/js/detectFBMeta.ts, src/js/detectIGMeta.ts, src/js/detectMSGRMeta.ts, src/js/detectWAMeta.ts, src/js/shared/MessageTypes.d.ts
Per title remove all the forks that were needed to support WA on older infra.
=> Remove codepaths supporting old Whatsapp site

src/js/__tests__/contentUtils-test.js, src/js/contentUtils.ts
Incorrectly snuck this in in #323 it was causing double checking of scripts.
=> Fix bad cleanup from #323

src/js/content/scanForCSS.ts, src/js/contentUtils.ts
Adding some checks to capture potential dubious CSS
=> Capture dubious CSS

yarn.lock
Upgrading to patches for CVE-2024-4067 and CVE-2024-37890
=> yarn upgrade ws and micromatch

src/js/background/getCFRootHash.ts
this change will be the new hostname (backwards compatibility on the old hostname will be maintained).
=> Update getCFRootHash.ts to new hostname

src/js/content/genSourceText.ts
Be more strict in handling sourceMappingURL ensuring they match against a predefined regex
=> More effectively handle sourceURL comments

_locales/en/messages.json, rollup.config.ts, src/css/popup.css, src/css/violations.css, src/html/popup.html, src/js/background/historyManager.ts, src/js/popup/popup.ts, src/js/popup/violation-list.ts
* New UI functionality to display past/current violations
* Will show the url and the time the violation occurred 
* If the violation was due to invalid hashes, an expandable section will be visible showing the invalid hashes and allowing the download of their source code
Other changes in this PR:
* Moved popup JS under js/popup
* Removed unnecessary use of Flexbox in main popup
=> Create a new Violation panel listing out details of past/current violations
