facebookincubator/meta-code-verify

config/v2/manifest.json
config/v3/manifest.json
src/js/contentUtils.js

Blocking the manifest from loading will now result in the user being warned.
Also, one of the console.log statements was way to verbose.

Flag non-loading manifest as a warning. Also, remove noisy console.log.

---

package.json

Right now if the `dist/` directory doesn't exist then the build fails. Running `makeBundle` first will ensure rollup creates that directory before be attempt to copy over static files

Fix 'build-local-dev' package command

---

config/v2/manifest.json
config/v3/manifest.json

These endpoints appear in some social widgets on external/third party sites and shouldn't have access to messaging content.
Test plan:
Loaded `facebook.com/sharer.php?...` and `facebook.com/sharer/sharer.php?...` and ensured the extension couldn't access the pages.

Add fb sharer plugins to exclude_matches

---

.eslintrc.json
config/v2/manifest.json
config/v3/manifest.json
src/js/background.js
src/js/config.js
src/js/contentUtils.js
src/js/popup.js
src/js/tab_state_tracker/FrameStateMachine.js
src/js/tab_state_tracker/StateMachine.js
src/js/tab_state_tracker/TabStateMachine.js
src/js/tab_state_tracker/tabStateTracker.js

tl;dr; The way the extension's icon and popup state get handled right now has a race condition.
Right now the extension's icon and popup state for a particular tab is handled/set by the extension's content scripts that are running on that tab. The issue with that is we can have multiple content scripts running per frame on the tab (e.g. one for the top-level frame/main page, and another for an iframe nested in that page). This means that if a particular content script sets that icon state to a "final" state, such as showing that verification failed for the page, another content script on the same tab can override that state, and change it to something else, like verification succeeded. For example, at:
* `t=0`: top frame content script sets state to PROCESSING
* `t=1`: nested iframe …

Have Background Script Handle Tab State

---

config/v2/manifest.json
config/v3/manifest.json
src/js/contentUtils.js
src/js/detectFBMeta.js

**NOTE:** This depends on PR #184, which should ideally be merged first and have its branch deleted so that this one merges directly onto `main`, and we get separate commits on main for each PR.
Our `exclude_matches` constraint on the manifest can be too greedy and can match with an endpoint that _should_ be checked by the extension, which is bad. To fix this, we can have the content script run on all facebook domains and use more stricter RegExps on the pathnames to determine whether or not the page should be checked by the extension. If they shouldn't they can push an IGNORE state transition, which'll either:
1. Change the tab's state to IGNORE and disable the extension's icon/popup, or
2. Change the tab's state to INVALID if there are other frames that are attempting to set their state …

Add ability to ignore pathnames inside content script

---

config/v2/manifest.json
config/v3/manifest.json
src/js/background.js
src/js/contentUtils.js
src/js/popup.js
src/js/tab_state_tracker/TabStateMachine.js
src/js/tab_state_tracker/tabStateTracker.js

**NOTE:** This depends on PR #185, which should ideally be merged first and have its branch deleted so that this one merges directly onto `main`, and we get separate commits on main for each PR.
Right now, we use the `"tabs"` permission to access the url of the current tab the popup is being accessed on to know which site's help center article (FB, Messenger, or WhatsApp) to open up when a Learn More link is clicked on. This results in a "Read your browsing history" permission message showing up for the extension:
We don't actually need this permission. [According to Chrome's docs](https://developer.chrome.com/docs/extensions/reference/tabs/#perms) we can use optional `host_permission`s to read the tab's url for specific domains. Or, alternatively, what this PR does is just have the …

Update popup help link logic to not use "tabs" permission

---

.eslintrc.json
build/rollup-plugin-static-files.mjs
package.json
rollup.config.js

Recent development on this codebase has made me  **really** want some sort of watch functionality that can re-bundle as soon as a relevant file changes. Luckily Rollup has that functionality, and we'll just need to merge other build commands, like copying files, formatting and linting, over to rollup, which should be fine since rollup was designed to have a plugin system that allows for intermediate custom steps in the build process.
This PR has rollup handle copying files over. I couldn't really find an existing plugin that has the functionality/flexibility that I was looking for, so I built a simple custom plugin that just uses node's `fs` module to perform file operations. This change has the added benefit of making the file operations platform agnostic and therefore able to run on …

Use rollup to copy static files

---

build/rollup-plugin-clean-once.mjs
package.json
rollup.config.js

**NOTE:** This depends on PR #187, which should ideally be merged first and have its branch deleted so that this one merges directly onto `main`, and we get separate commits on main for each PR.
Recent development on this codebase has made me  **really** want some sort of watch functionality that can re-bundle as soon as a relevant file changes. Luckily Rollup has that functionality, and we'll just need to merge other build commands, like copying files, formatting and linting, over to rollup, which should be fine since rollup was designed to have a plugin system that allows for intermediate custom steps in the build process.
This PR moves another file operation to rollup: it adds a custom plugin to delete output directories **once** (so they don't get removed multiple times when running …

Have rollup clean output dirs once before each build

---

build/rollup-plugin-prettier-build-start.mjs
build/rollup-plugin-static-files.mjs
build/rollup-plugin-watch-additional.mjs
build/utils.mjs
package.json
rollup.config.js

**NOTE:** This depends on PR #189 which should ideally be merged first and have its branch deleted so that this one merges directly onto `main`, and we get separate commits on main for each PR.
Recent development on this codebase has made me  **really** want some sort of watch functionality that can re-bundle as soon as a relevant file changes. Luckily Rollup has that functionality, and we'll just need to merge other build commands, like copying files, formatting and linting, over to rollup, which should be fine since rollup was designed to have a plugin system that allows for intermediate custom steps in the build process.
This adds in a custom rollup plugin to watch for changes in static files in certain folders. Why not re-use the custom static files plugin I created in #187 to watch …

Create rollup plugin to watch static files

---

src/js/detectFBMeta.js

Nothing appears to be wrong with this route, and an endpoint like `/donate/<ID>` is susceptible to 404 redirects, meaning the 404 page would get ignored by the extension, which is not what we want.

Remove /donate RegExp from excluded pathnames

---

src/js/detectFBMeta.ts

This prevents that extension's content script from running on iframes containing the page plugin (example site with plugin:  https://www.chinadiscovery.com/chinese-visa/144-hour-visa-free.html)

Exclude the page plugin from triggering the extension

---

config/v2/manifest.json
config/v3/manifest.json
src/js/detectFBMeta.ts
src/js/tab_state_tracker/TabStateMachine.ts

- Extension will still be disabled for any external sites that have Facebook plugins which embed iframes (e.g. https://www.chinadiscovery.com/chinese-visa/144-hour-visa-free.html)
- All first party pages, and Facebook plugins in first party sites are no longer allowed to disable the extension, and will be marked as invalid whenever a content script from a frame attempts to disable the extension for the tab

Prevent disabling extension on first party sites

---

config/v2/manifest.json
config/v3/manifest.json
src/js/background.js
src/js/contentUtils.js

We want to ensure that the CSP headers are blocking unsafe evals through enforcement.
When this is not possible we need to ensure that CSP headers are forcing reporting on unsafe-evals and we listen to the violation events and update CodeVerify's status accordingly.

Add checks for CSP enforcement

---

src/js/__tests__/contentUtils-test.js
src/js/contentUtils.js

Recursion code was messy and visiting nodes more than needed. This set of changes centralizes the recursion logic in one place.
Flow:
1. Script mounts, `document.getElementsByTagName('*')` fetches all nodes and all nodes are verified via `checkNodeForViolations` , scripts are also stored as necessary via `storeFoundJS`
2. MutationObserver detects additions/changes
a.  Listen to added childNodes, call `hasInvalidScripts` on each node.
b.  Listen to changed attributes and call `checkNodeForViolations` on affected node
All the recursion happens in `hasInvalidScripts`. Recursion is necessary since the MutationObserver only detects top level added nodes but we need to check their children.
```
export function hasInvalidScripts(scriptNodeMaybe, scriptList) {
// if not an HTMLElement ignore it! …
```

Fix recursion new

---

src/js/background/setupNoCacheListeners.ts

Was spewing a bunch of unnecessary errors here by catching requests from other extensions, we only care about the case where the `tabId` is set in the first place.

Avoid throwing unnecessary errors when listening to uncached scripts

---

package.json
src/js/__tests__/contentUtils-test.js
src/js/background.ts
src/js/content/checkCSPHeaders.ts
src/js/content/checkElementForViolatingAttributes.ts
src/js/content/checkElementForViolatingJSUri.ts
src/js/content/downloadJSArchive.ts
src/js/content/updateCurrentState.ts
src/js/contentUtils.ts
src/js/index.d.ts
src/js/shared/MessagePayload.d.ts
src/js/shared/isFbOrMsgrOrigin.ts
yarn.lock

- Upgrade rollup eslint plugin, it seems to be incorrectly complaining about nullish coalescing and optional chaining operators which TS compiles into statements using `var`
- contentUtils.js -> contentUtils.ts
- Pull our methods for validating nodes
- Module level constants to SNAKE_UPPER_CASE
- Change some named exports to default exports
- Create shared util to check for FB/MSGR origin
- **Created type for content -> BG message payloads as we were sending a lot of unused values.**

Further improve TS coverage

---

package.json
src/js/__tests__/checkCSPHeaders-test.js
src/js/background.ts
src/js/background/setupCSPListener.ts
src/js/content/checkCSPHeaders.ts
src/js/contentUtils.ts
src/js/shared/MessageTypes.d.ts

https://w3c.github.io/webappsec-csp/#multiple-policies
We need to be more careful in avoiding false positives when there are potentially multiple policies set.

Ensure CSP checks work when there are multiple CSP headers

---

src/js/__tests__/checkElementForViolatingAttributes-test.js
src/js/__tests__/contentUtils-test.js
src/js/content/parseFailedJSON.ts
src/js/contentUtils.ts

It seems that we are incorrectly validating JS when it comes from a different manifest version, this change makes sure script tags are attributed to the correct version.

Fix support for multiple manifest versions

---

src/js/config.ts

Firefox 113 added support for `CompressionStream` but it still does not support `showSaveFilePicker` which unintentionally started showing the download button in the extension.

Fix DOWNLOAD_JS_ENABLED feature flag

---

src/js/contentUtils.ts

#239 made an incorrect assumption that loaded script would be handled before the manifest this leaded to some scripts being skipped from being processed.
This fix ensures that if scripts with src tags are loaded before the manifest they are moved correctly to the appropriate `Map` when the manifest is loaded.

Fix versioning bug in #239

---

src/js/background/setupCSPListener.ts

It seems that some browser implementations of webRequest have these uppercase, lowercasing for consistency.

Cast http checked headers to lowercase in CSP listeners

---

src/js/contentUtils.ts

If scripts are detected before a `currentFilterType` is set, they might end up never being checked. This isn't an issue on facebook.com where currentFilterType eventually is set to both which [ends up checking all scripts](https://github.com/facebookincubator/meta-code-verify/blob/main/src/js/contentUtils.ts#L348), but on ig/msgr this could end up in these scripts being ignored if they are detected before the type is set. 
This fixes that.

Fix case where scripts from non-main thread could potentially be ignored

---

src/js/background/setUpWebRequestsListener.ts

`isMetaInitiatedResponse` was erroring because we added this check before checking for extensions which have no `initiator` field.
This commit moves the extension check to preceed the initiator check

fix extension check

---

src/js/background/tab_state_tracker/StateMachine.ts

This should be a valid state transition.
Test plan:
- Enabled some extensions until I got a risk warning
- Injected script from console and ensure state transitioned to invalid

Correctly update states from RISK -> INVALID

---

src/js/contentUtils.ts
src/js/detectFBMeta.ts
src/js/detectIGMeta.ts
src/js/detectMSGRMeta.ts
src/js/detectWAMeta.ts

Fixes a regression caused by https://github.com/facebookincubator/meta-code-verify/pull/261 where `excludedPathnames` was missing:
- `excludedPathnames` is no longer optional.
- Resorted config definitions and entries to be alphabetical for easier reading.

Fix regression with missing excludedPathnames

---

src/js/__tests__/contentUtils-test.js
src/js/contentUtils.ts

Complimentary fix to https://github.com/facebookincubator/meta-code-verify/pull/264 for https://github.com/facebookincubator/meta-code-verify/issues/254
Ensure that if an empty script without a src is injected we do not store it for processing, if we later inject content into this script our Mutation Observers should now correctly detect and verify it.

Fix CV on WA

---

src/js/__tests__/checkDocumentCSPHeaders-test.js
src/js/__tests__/checkWorkerEndpointCSP-test.js
src/js/content/checkCSPForEvals.ts

This resets the behavior of the CSP checks back to how they were before #268. I will re-introduce this `invalidateAndThrow` behavior in a later PR, but reverting this now makes it easier to see what is going on.
In following PRs I intend to
- Refactor the tests for this code so as to be more granular. Right now we are running tests at the `checkDocumentCSPHeaders` level, but as we add more individual checks (e.g. for unsafe-inline) this will start to make it unclear which rule an individual test is for.
- Re-introduce the `invalidateAndThrow`, but at the `checkDocumentCSPHeaders` level. This will allow the individual checks (checkCSPForEvals, checkCSPForWorkerSrc) to be flexibly used as checks, and more easily tested, while still retaining the invalidate/throw behavior.
- Add a …

Revert checks back to not throwing

---

src/js/__tests__/parseFailedJSON-test.js
src/js/content/parseFailedJSON.ts
src/js/contentUtils.ts

@aselbie pointed out that I introduced a bug with https://github.com/ezzak/meta-code-verify/commit/6b168b6f359194d223b325744867b2a38c3a2080
We should continue to pass the node by reference here so that when it's text content changes we correctly parse.

Fix node JSON parsing

---

src/js/background.ts

This made it harder to dig into object logged by the bg/service-worker.

Remove unnecessary stringify in bg logging

---

src/js/__tests__/checkDocumentCSPHeaders-test.js
src/js/content/checkDocumentCSPHeaders.ts

Refactor the tests for this code so as to be more granular. Right now we are running tests at the checkDocumentCSPHeaders level, but as we add more individual checks (e.g. for unsafe-inline) this will start to make it unclear which rule an individual test is for.

Make document CSP check tests more granular

---

.gitignore

Newer versions of yarn use `.yarnrc.yml` instead of `.yarnrc`. Accidentally committing this file can break the build in CD, so I recommend we ignore it for now.

Ignore .yarnrc.yml

---

src/js/__tests__/checkWorkerEndpointCSP-test.js
src/js/content/checkWorkerEndpointCSP.ts

This PR should be a pure refactor. I'm making the follow changes:
1. Extract the bulk of `checkWorkerEndpointCSP` into a new function called `isWorkerEndpointCSPValid`. This new function should have no side-effects (no throwing, no invalidation) so that it is reusable and easier to test. `checkWorkerEndpointCSP` now calls this new function and performs any of the side-effects required.
2. The existing `checkWorkerEndpointCSP` function was performing three distinct tasks: 1) checking CSP for evals, 2) validating the worker-src, 3) Validating the absence of blob/data. (1) was already split out into a separate function, and I've done the same for (2) (`isWorkerSrcValid`) and (3) (`areBlobAndDataExcluded`). In the next PR I will make the tests for these functions more granular.
3. Updated the …

Refactor checkWorkerEndpointCSP

---

src/js/__tests__/checkDocumentCSPHeaders-test.js
src/js/content/checkCSPForEvals.ts
src/js/content/checkDocumentCSPHeaders.ts
src/js/content/checkWorkerEndpointCSP.ts
src/js/contentUtils.ts

Changes:
- For all our CSP checks, adds a "reason" field as the return when validation fails. This allows us to simplify handling in a single place.
- Update the handling of these error to use `invalidateAndThrow` to avoid strange side-effects after invalidation.
- Make the two top level checker functions (`checkDocumentCSPHeaders`, `checkWorkerEndpointCSP`) return void to better reflect how they actually behave (either they succeed or they throw, no need for a return).
Note: the tests have not materially changed, they've just been reformatted to reflect the return being a tuple.

Add reason to CSP checker returns

---

src/js/background/tab_state_tracker/TabStateMachine.ts

This error would fire every time we try to update the popup contents even though a popup is not open. This change suppresses it from polluting the logs.

Finally kill mysterious bg error

---

src/js/shared/sendMessageToBackground.ts

We subtly changed the behavior here with the TS strictify-ing.
Chrome APIs are not happy when we send an empty callback but never call it, instead we should not send this argument. The TS definitions are poorly typed.
https://github.com/ezzak/meta-code-verify/blob/main/src/js/background.ts#L101-L105
This was causing a ton of log spew

Fix content log spew

---

src/js/__tests__/checkDocumentCSPHeaders-test.js
src/js/__tests__/parseFailedJSON-test.js
src/js/content/parseCSPString.ts

When we parse CSP we should make sure that we correctly check for mixed/lower/upper case directives/values

Ensure support for mixed-case csp values/keys

---

src/js/__tests__/parseCSPString-test.js
src/js/content/parseCSPString.ts

We should continue to correctly parse other directives even when a certain expective directive (key) is invalid.
The browser behavior is to log a console error but still apply the CSPs non the less, it just complains that that the empty character(s) is an invalid key.

Correct parse CSP even when parts of it are invalid

---

src/js/__tests__/checkCSPForUnsafeInline-test.js
src/js/content/checkCSPForUnsafeInline.ts
src/js/content/checkDocumentCSPHeaders.ts
src/js/content/checkWorkerEndpointCSP.ts

The extension will now invalidate if the documents CSP allows unsafe-inline execution.
**Testing**
- Checked on Chrome, Firefox and Edge.
- Correctly handles (green check mark) FB, MSGR and WA.
- Correctly handles Instagram, but unfortunately that means failure at the moment, because there is an extra frame loaded by IG that still has `unsafe-inline`. Submitting for review but we should hold off on merging/releasing until that issue can be addressed.

Enforce the absence of unsafe-inline on Document CSPs

---

src/js/contentUtils.ts
src/js/shared/nestedDataHelpers.ts

Currently if we encounter a script that has packages in both the main and longtail manifests, something like `data-btmanifest="1009592080_main,1009592080_longtail"`, we will parse its "type" as `main,1009592080_longtail`. By virtue of the rest of the code this does actually end up working, but leaves us open to bugs introduced in future changes.
This diff updates the parsing to first check if the manifest field has both types, and if so, use "BOTH" as the type, which will ensure that this script will not be processed until both manifests have been loaded.
- Change `dataBtManifest == null` to `!dataBtManifest` so that we invalidate and throw if `data-btmanifest` is empty.
- While writing this code it became clear that in code path where `scriptsShouldHaveManifestProp` is true, we will …

Handle scripts with packages from both manifests

---

src/css/popup.css

Download popup rendering somehow got messed up at some point, unsure when this regression was introduced.
+ prettier formatting

Fix download popup rendering

---

src/js/__tests__/getCSPHeadersFromWebRequestResponse-test.js
src/js/shared/getCSPHeadersFromWebRequestResponse.ts

Turns out in some browsers, webRequest concats the two headers together, this should add support fort hat.

Add support for multiple CSPs within the same HTTP header

---

src/js/background/setupCSPListener.ts

In order to explore the possibility of supporting Safari we need a workaround for the tabId values reported by webRequest.
See issue here https://developer.apple.com/forums/thread/668159

Workaround for storing CSP values in Safari

---

config/v2/manifest.json

Safari does seems to treat this as an exact match
With wildcard tail

Tweak cloudflare endpoint permission item in manifest to allow Safari to hit it

---

src/js/background/tab_state_tracker/TabStateMachine.ts

I really don't have a good explanation for this one.
All I know is that if these function are references without having a direct code call, they end up doing nothing in Safari. Rewrote it so that this is not the case. aAlso hide/show actions do not exist in Safari. No errors were showing up when this failed.

Tweak v2 chrome actions for Safari

---

src/js/background/setupCSPListener.ts
src/js/background/validateSender.ts

I have been unable to pinpoint the cause of this. But it seems that due to a recent regression CV is failing on prerendering despite me being confident in the fix back in #262.
I've made our checks more explicit here to distinguish between requests from a prerendered page and active page.
I've been unable to pinpoint the cause of this regression, I'm certain this worked before. I tried testing on Chromium versions 116, 117, 118, 119 and was able to repro there too. 
Tested with/without prerendering.

Fix failures on prerendering 

---

src/js/config.ts
src/js/content/ensureManifestWasOrWillBeLoaded.ts
src/js/contentUtils.ts

Scripts from an invalid manifest can possible get CV stuck in a processing state, this ensures that CV gets into an invalid state if such a script is detected; after an adequate timeout.

Tackle scripts claiming to belong to an invalid manifest

---

src/css/popup.css
src/html/popup.html
src/js/popup.ts

Using `img` tags to render SVGs was problematic and causing bad rendering.

Fix SVGs rendering on Safari

---

src/css/popup.css

We're hiding popup contents on first render which was causing flickering, I've updated the initial css to not show content meant to be hidden in the first place.
Checked to make sure things still render as expected.

Fix popup flickering

---

src/js/background/validateSender.ts

I believe I incorrectly introduced this, it was not being suppressed when I added it locally and perhaps something was behind in my local packages.

Fix a warning in builds

---

src/css/popup.css
src/html/popup.html

Fix styling of close button

---

src/js/__tests__/contentUtils-test.js
src/js/contentUtils.ts

When writing the last PR I noticed that we weren't explicitly checking for the presence of the type of the manifest when parsed from the attribute, changed the logic to explicitly check for it. 
Ensured test was failing before and passing after.

Improve manifest data attribute check to ensure both version/type are set

---

src/js/config.ts

This referenced was missed by me when I last fixed/unified icons across manifests.
This changes addresses the following error

Fix an error that was being caused by a bad icon reference

---

src/js/background/setUpWebRequestsListener.ts

This is a bug fix for issue #334 where the **x-content-type-options** header is only detected when the header name is lowercase. This has been fixed so that the header detection is now case-insensitive, allowing seamless support for other websites.

X-Content-Type-Options header detection is now case insensitive #334

---

src/js/config.ts
src/js/content/downloadJSArchive.ts
src/js/contentUtils.ts

More missed code from #323
We don't allow any inline scripts given `unsafe-inline` checks, so it makes no sense to check the content of these scripts.
This also allows us to remove logic that supported scripts inserted by other extensions.
Tested on FB/MSGR/IG/WA

Cleanup unused codepaths

---

src/js/config.ts
src/js/content.ts
src/js/content/contentUtils.ts
src/js/content/downloadArchive.ts
src/js/popup.ts

Various cleanup/refactors post CSS support, mainly to highlight in naming/comments that JS and CSS are handled.

Cleanups post CSS support

---

src/js/__tests__/parseCSPString-test.js
src/js/content/parseCSPString.ts

https://w3c.github.io/webappsec-csp/#framework-directives
According to the spec whitespace characters can be used to separate CSP directive values

When checking CSP ensure other whitespace characters are accounted for 

---

config/v2/manifest.json
config/v3/manifest.json
package.json
src/js/background.ts
src/js/background/historyManager.ts
src/js/background/setUpWebRequestsListener.ts
src/js/background/setupCSPListener.ts
src/js/background/tab_state_tracker/TabStateMachine.ts
src/js/content/checkWorkerEndpointCSP.ts
src/js/content/hasVaryServiceWorkerHeader.ts
src/js/shared/getCSPHeadersFromWebRequestResponse.ts
yarn.lock

* Users should be able to look back at previous failures to investigate the cause of violations
* Use a combination [Extension Storage](https://developer.chrome.com/docs/extensions/reference/api/storage) and [OPFS](https://developer.mozilla.org/en-US/docs/Web/API/File_System_API/Origin_private_file_system) to keep track of violations
* This PR incorporates the use of extension storage to keep track of violations per tab/session including hashes which where the cause of failures
* The source code of said hashes will be stored in OPFS
* This includes a cleanup mechanism to remove entries older than 120 days, UI will allow manual deletion of entries
* UI to come separately
* This also includes a bump of `@types/chrome` which was needed for some of the used APIs
Cleanup

Add history tracking storage functionality for violation

---

src/js/background.ts
src/js/config.ts

* These checks are not necessary as the browser cleans this up when the extension is backgrounded or browser is closed

Remove manifest timeout

---

_locales/en/messages.json
src/css/popup.css
src/html/popup.html
src/js/popup.ts

Rewrite UI using Web Components (https://developer.mozilla.org/en-US/docs/Web/API/Web_components/Using_custom_elements)
* The UI is really hard to work with and in preparation for some upcoming changes I took the liberty to rewrite it using Web Components
* Component: `state-element` handles displaying different extension states: 'loading', 'warning_risk', 'warning_timeout', 'error', 'valid', 'download'. `menu` state will be handled in a subsequent PR
* Component: `popup-header` subcomponent within `state-elemnt` that renders the top header
* Standardized buttons/layouts inside a state
With Download support:
<video src="https://github.com/user-attachments/assets/6287ed5c-d943-4d34-9e42-50b462e8c0c0" width="300" />
Without Download support:
<video …

Rewrite UI with Web Components

---

src/js/background.ts
src/js/background/historyManager.ts
src/js/content.ts
src/js/globals.ts
src/js/index.d.ts
src/js/popup/popup.ts
tsconfig.json

1. Recent PRs created some issues on Firefox, the Promise based `chrome.` APIs in Firefox/Safari must use `browser.` this is why we haven't usually used these in the past. But I want to be able to use this syntax, so I've added some global logic to magically use `browser.` when it's available (non-chromium browsers) and fallback to `chrome.` when it's not, this will allow the Promise based APIs to always work.
2. I also realized we're transpiling to polyfill async/await which we don't really need to, upped the target ES version in `.tsconfig`
3. `storage.getKeys()` JUST got added to Firefox https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/143#changes_for_add-on_developers so I'm changing things to use `storage.get(null)` instead since it has access to similar information …

Fix multiple issues relating to async/await

---

package.json
src/js/background.ts
src/js/background/tab_state_tracker/TabStateMachine.ts
src/js/content.ts
src/js/content/manualCSSInspector.ts
src/js/content/parseFailedJSON.ts
src/js/popup/popup.ts
yarn.lock

Upgrade eslint version to match prior typescript bump

Upgrade eslint to match new typescript version

---

src/js/background/historyManager.ts

In Chrome tab ID would most likely be reused mostly on refresh, but Firefox tab Ids count upward from 1 so Ids are more likely to clash. In this case maintain the violations.

Maintain violations when tab ID is reused
